[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false

# 統合システム用追加設定
[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
4.2 統合設定ファイル
integration_config.json
json{
  "system_version": "integrated_v1.0",
  "integration_date": "2025-06-18",
  "features": {
    "dataset_selection": true,
    "system_comparison": true,
    "performance_analysis": true,
    "advanced_settings": true
  },
  "default_settings": {
    "analysis_mode": "両方比較",
    "selected_datasets": ["LFW", "ImageNet_Animals", "Food101", "Places365"],
    "confidence_threshold": 0.7,
    "enable_caching": true
  },
  "performance_targets": {
    "accuracy_improvement": 0.10,
    "max_processing_time": 30,
    "supported_categories": 8
  }
}